# Generated by Django 3.0 on 2019-12-16 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('short_url', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Short URL')),
                ('origin_url', models.CharField(max_length=2100, verbose_name='Origin URL')),
                ('click_counter', models.BigIntegerField(default=0, verbose_name='All clicks')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
